name: "Build Totem"
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["totem_left", "totem_right"]'
      kconfig: '["CONFIG_ZMK_SLEEP=y"]'
      clipboard: '["mac"]'
      alphas: '["QWERTY"]'
      nav: '["invertedT"]'
      layers: '["flip"]'
