name: "Build Totem with MouseKeys"
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["totem_left", "totem_right"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYPR"]'
      kconfig: '["CONFIG_ZMK_SLEEP=y\nCONFIG_ZMK_MOUSE=y"]'
      clipboard: '["Mac"]'
      alphas: '["QWERTY"]'
      nav: '["invertedT"]'
      layers: '["flip"]'
