name: "Build Totem"
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflow/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["totem_left", "totem_right"]'
      # kconfig: '["CONFIG_ZMK_SLEEP=y"]'
