# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'min34 with outboard'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["min34_left", "min34_right"]'
